import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import '../globals.css';
import Footer from '@/components/client/Layout/Footer';
import Navbar from '@/components/client/Layout/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[#f6f7fa]">
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}
